// GENERATED by scripts/update-reviewed-dates.ts. Do not edit by hand.
//
// The date each static page's content last changed, from git history. Feeds
// `lastmod` for the static half of the sitemap. Regenerate after a content
// change:  npx tsx scripts/update-reviewed-dates.ts
//
// Being stale only makes a date older than reality, which is the safe direction:
// a `lastmod` that moves on every deploy is the signal crawlers discount.

/** Static route path (as in config/routes.ts) to ISO date of its last content change. */
export const PAGE_UPDATED: Record<string, string> = {
  "": "2026-07-26",
  "/about": "2026-07-26",
  "/approach": "2026-07-26",
  "/blog": "2026-07-26",
  "/careers": "2026-07-26",
  "/case-studies": "2026-07-26",
  "/contact": "2026-07-26",
  "/data-ai": "2026-07-26",
  "/faq": "2026-07-26",
  "/industries": "2026-07-26",
  "/life-at-viewnear": "2026-07-26",
  "/migrations": "2026-07-26",
  "/nearshore": "2026-07-26",
  "/nearshore/monterrey": "2026-07-26",
  "/partnership": "2026-07-26",
  "/platform": "2026-07-26",
  "/press": "2026-07-26",
  "/pricing": "2026-07-26",
  "/privacy": "2026-07-26",
  "/resources": "2026-07-26",
  "/security": "2026-07-26",
  "/services": "2026-07-26",
  "/snowflake-consulting-services": "2026-07-26",
  "/terms": "2026-07-26",
};
