// Spanish (es) overlay. Keyed by slug. Optional: empty means the row falls back to English. Filled by the content-translation phase.
export const siteSettingsEs: Record<string, unknown> = {
  hero: {
    headline: "Lo difícil de la IA son los datos. Construimos ambas cosas.",
    subhead:
      "Diseñamos los cimientos de datos, gobernamos lo que circula por ellos y ponemos la IA a trabajar a escala empresarial: las decisiones, las operaciones y los sistemas que las ejecutan.",
  },
  stats: [
    { label: "Nivel de partner de Snowflake", value: "Premier" },
    { label: "Años construyendo datos e IA empresarial", value: "15+" },
    { label: "Certificaciones SnowPro", value: "10" },
    { label: "Oficinas de entrega: Austin y Monterrey", value: "2" },
  ],
  partnership: {
    title: "El Snowflake Premier Partner en las Américas.",
    points: [
      {
        title: "Snowflake Premier Partner",
        body: "El estatus Premier pone a ingenieros con certificación SnowPro en el trabajo, respaldados por un historial de entrega verificado y de extremo a extremo en las Américas: desde la arquitectura y la migración hasta la analítica y la IA en producción.",
      },
      {
        title: "Snowflake CoCo Preferred Partner",
        body: "Como Snowflake CoCo Preferred Partner, construimos con Snowflake CoCo, el agente de codificación, para que los productos de datos y los casos de uso de IA lleguen más rápido: gobernados y validados antes de llegar a producción.",
      },
      {
        title: "Adquisición de Snowflake, simplificada",
        body: "Snowflake se adquiere directamente a través de Viewnear. Es basado en consumo (el negocio paga por el cómputo y el almacenamiento que usa) y simplificamos el compromiso de capacidad, los términos comerciales y la gestión de cuenta bajo un único partner de confianza.",
      },
      {
        title: "Entrega de extremo a extremo",
        body: "Desde la arquitectura y la migración hasta la ingeniería de datos, la analítica y la IA en producción, un único equipo responsable lleva el trabajo de extremo a extremo, y los equipos internos lo aprenden mientras construimos.",
      },
      {
        title: "El equipo local de las Américas",
        body: "Dos oficinas, Austin y Monterrey, ambas en horario del centro, para clientes en toda América. Conocemos el panorama regional de datos y estamos aquí para el largo plazo, no solo para el primer despliegue.",
      },
    ],
  },
  contact: {
    email: "contact@viewnear.com",
    blurb:
      "Viewnear atiende cada mensaje con una llamada breve y luego una propuesta clara: los primeros casos de uso, un plan sprint por sprint y un precio, ya sea modernizar sobre Snowflake o empezar desde cero.",
  },
};
export const faqsEs: unknown[] = [
  { category: "Alianza y certificaciones", q: "¿Qué es un Snowflake Premier Partner y cómo se verifica ese estatus?", a: "Viewnear es Snowflake Premier Partner y Snowflake CoCo Preferred Partner, con ingenieros con certificación SnowPro y un historial de entrega verificado en las Américas." },
  { category: "Alianza y certificaciones", q: "¿Qué desbloquea realmente el estatus Premier?", a: "Profundidad y una línea directa con Snowflake. El estatus Premier refleja entrega certificada en todo el stack de Snowflake, y significa que trabajamos junto al equipo de cuenta de Snowflake del cliente en arquitectura y entrega, sobre el stack actual (Cortex, Openflow, Horizon Catalog, CoCo y CoWork). Nos asociamos con Snowflake para llevar cada proyecto a un resultado exitoso." },
  { category: "Alianza y certificaciones", q: "¿Cómo funciona el precio de Snowflake y se puede adquirir a través de un partner?", a: "Snowflake es basado en consumo: el negocio paga por el cómputo (créditos) y el almacenamiento que realmente usa, de modo que el costo de operación se ajusta al trabajo. La capacidad de Snowflake se puede adquirir a través de Viewnear para simplificar los términos comerciales y la gestión de cuenta bajo un único partner responsable." },
  { category: "Entrega y proyectos", q: "¿Cuánto tarda una implementación de Snowflake?", a: "Una primera construcción en producción se dimensiona en 8 a 16 semanas, según el volumen de datos, la complejidad de las fuentes y los casos de uso en scope. Lo que lo mantiene real: un discovery que fija el scope desde el inicio, sprints impulsados por casos de uso con software funcionando en cada demo, y pruebas corriendo en paralelo con la construcción, de modo que el valor se muestra desde el primer sprint." },
  { category: "Entrega y proyectos", q: "¿Cómo se reduce el riesgo de un proyecto grande de Snowflake?", a: "Probamos el enfoque con un POC acotado antes de escalar, realizamos juntas de seguimiento periódicas con puntos de decisión claros, e integramos la habilitación desde el primer día, para que los equipos internos puedan operar y extender el trabajo sin nosotros." },
  { category: "Entrega y proyectos", q: "¿Se puede migrar un data warehouse existente a Snowflake?", a: "Sí. Migramos desde Teradata, Oracle, Hadoop y SQL Server, y gestionamos toda la entrega técnica y la gobernanza del programa." },
  { category: "Entrega y proyectos", q: "¿Se puede integrar Snowflake con ERP, CRM y sistemas operativos?", a: "Sí, en ambas direcciones. Openflow y Zero-Copy Integrations traen datos desde sistemas como SAP, Salesforce y Workday, y entregamos información de vuelta a través de Snowsight, aplicaciones de Streamlit, APIs y agentes integrados donde los equipos trabajan." },
  { category: "Nearshore y el equipo de entrega", q: "¿Dónde se ubican los equipos nearshore de entrega de Snowflake?", a: "Nuestro centro de entrega nearshore está en Monterrey, Nuevo León, México, con la dirección en Austin, Texas. La mayor parte de la ingeniería está en Monterrey y la dirección en Austin, con algunos roles remotos en toda América. Atendemos clientes en toda América: Canadá, Estados Unidos, México, LATAM y el Caribe." },
  { category: "Nearshore y el equipo de entrega", q: "¿En qué horario trabaja el equipo nearshore?", a: "Monterrey mantiene el horario estándar del centro (CST) todo el año, porque México ya no aplica el horario de verano. El centro de EE. UU. cambia a CDT de marzo a noviembre, así que en esos meses el reloj de Monterrey marca una hora antes. El equipo trabaja en el horario laboral del cliente de cualquier forma: la jornada se traslapa por completo y las preguntas se responden el mismo día, no al día siguiente." },
  { category: "Nearshore y el equipo de entrega", q: "¿Qué tan lejos está Monterrey de Estados Unidos y el equipo puede trabajar presencialmente?", a: "Monterrey está a unos 225 kilómetros de la frontera con Texas, con vuelos directos a las principales ciudades de Estados Unidos en una a cuatro horas. Eso hace que el trabajo presencial sea práctico y no simbólico: talleres de discovery, sesiones de arquitectura y juntas de seguimiento pueden ocurrir en la oficina del cliente sin dos días de viaje de cada lado." },
  { category: "Nearshore y el equipo de entrega", q: "¿Podemos visitar el centro de entrega en Monterrey?", a: "Sí. Los clientes son bienvenidos en nuestra oficina de Monterrey, y las visitas son comunes al inicio de un proyecto: conocer a los ingenieros que harán el trabajo, recorrer la arquitectura en un pizarrón y ver cómo opera el equipo día a día." },
  { category: "Nearshore y el equipo de entrega", q: "¿En qué se diferencia nearshore de offshore para una construcción de datos e IA?", a: "El trabajo de Snowflake e IA es iterativo: perfilar los datos, modelarlos, probar un caso de uso, ver el resultado, ajustar. Ese ciclo es rápido cuando un bloqueo planteado a las 10am se resuelve para la comida, y doloroso cuando cada ida y vuelta espera toda la noche. El modelo nearshore mantiene ese ciclo dentro de una misma jornada, con trabajo en pareja en vivo y sprint reviews a las que el equipo del cliente sí puede asistir. Offshore puede ganar en tarifario; rara vez gana en tiempo hasta un resultado funcionando." },
  { category: "Nearshore y el equipo de entrega", q: "¿El equipo trabaja en inglés o en español?", a: "En ambos. Cada ingeniero tiene dominio del inglés y el equipo es completamente bilingüe, así que las sesiones de trabajo, la documentación y la habilitación ocurren en el idioma que el equipo prefiera. No hay una capa de traducción entre el cliente y las personas que hacen el trabajo." },
  { category: "Aspectos comerciales", q: "¿Qué modelos de colaboración existen?", a: "Tres, y se pueden combinar: entrega de resultado fijo con precio atado a un resultado definido, capacidad flexible cuando el scope sigue moviéndose, y un equipo integrado o dedicado que trabaja dentro de sus sprints, repositorios y estándares. Quienes buscan extensión de equipo o staff augmentation suelen elegir el modelo integrado. Los tres se miden por resultados y no por horas." },
  { category: "Seguridad y plataforma", q: "¿El trabajo permanece dentro de nuestro entorno y bajo nuestros controles?", a: "Sí. La construcción corre en la cuenta de Snowflake, los repositorios y el CI del cliente, bajo los controles de acceso y el proceso de cambios del cliente. Los ingenieros trabajan como identidades nombradas con acceso de mínimo privilegio, bajo términos de confidencialidad firmados, y el linaje de Horizon Catalog mantiene una traza auditable de lo que cambió." },
  { category: "Aspectos comerciales", q: "¿Cómo se fija el precio de un proyecto?", a: "Los proyectos se dimensionan según el volumen y la complejidad de los datos, la cantidad de casos de uso de analítica/IA, el tamaño del equipo y el cronograma. Acordamos el scope y el precio por adelantado y ofrecemos modelos de resultado fijo, capacidad flexible y equipo integrado: un partner medido por el resultado, no por las horas facturadas." },
  { category: "Aspectos comerciales", q: "¿Los partners de Snowflake publican precios estándar?", a: "No. No hay dos entornos de datos iguales, así que fijamos el precio según el trabajo. Con los objetivos y las restricciones sobre la mesa, respondemos con un modelo, un plan y un precio." },
  { category: "Seguridad y plataforma", q: "¿Cómo se mantienen seguros los datos durante un proyecto de Snowflake?", a: "Construimos sobre la plataforma certificada de Snowflake y la extendemos con acceso de mínimo privilegio, linaje y clasificación de PII con Horizon Catalog, Horizon Context para que cada persona y cada agente de IA trabaje desde el mismo contexto de negocio confiable, residencia de datos por región, y controles listos para auditoría, todo configurado según el sector del cliente." },
  { category: "Seguridad y plataforma", q: "¿Conviene que una construcción en Snowflake sea nativa o use herramientas de terceros?", a: "Lideramos con el stack nativo de Snowflake (Openflow, Snowpark, Horizon Catalog, Cortex, Snowsight, Streamlit, más el agente de codificación Snowflake CoCo y el agente de IA CoWork) para que la gobernanza y el contexto de IA (Horizon Context) se mantengan en un solo lugar. dbt es el único framework externo que operamos, de forma nativa contra Snowflake." },
  { category: "Contratación y revisión de proveedores", q: "¿Qué acuerdos rigen un proyecto de datos e IA con Viewnear?", a: "Cada proyecto de Viewnear se rige por un acuerdo escrito independiente que establece el alcance, las tarifas, los plazos y las obligaciones; cuando ese acuerdo entra en conflicto con los términos del sitio, prevalece el del proyecto. El trabajo de costo fijo se documenta como un enunciado de trabajo con scope definido, con hitos, puntos de decisión y control de cambios si el scope varía; el trabajo por tiempo y materiales corre contra un backlog priorizado que el negocio controla. Un discovery breve fija el scope y devuelve un precio firme antes de comprometer un desarrollo, y los ingenieros trabajan bajo términos de confidencialidad firmados." },
  { category: "Contratación y revisión de proveedores", q: "¿Cómo atiende Viewnear una revisión de seguridad de proveedores o un cuestionario de seguridad?", a: "Viewnear atiende una revisión de seguridad de proveedores explicando cómo se cumple cada requisito, ya sea un punto único como residencia de datos, certificaciones o auditoría, o un cuestionario completo. El punto de partida publicado es la página de Seguridad y confianza de Viewnear, que divide la respuesta en dos: el entorno hereda las certificaciones de Snowflake, auditadas de forma independiente (SOC 2 Type II e ISO 27001 en todas las ediciones; los datos de salud y de tarjetas requieren Business Critical o VPS), y Viewnear aplica sus propios controles de entrega en cada proyecto. Esos controles son acceso con privilegios mínimos, linaje y auditabilidad, clasificación de PII, residencia de datos por región, gestión de secretos y claves, y prácticas de entrega seguras, que significan revisión de código, cuentas de entrega con privilegios mínimos y separación de entornos." },
  { category: "Contratación y revisión de proveedores", q: "¿Los datos salen de la región del cliente cuando la entrega de Snowflake ocurre desde México?", a: "Los datos permanecen en la cuenta de Snowflake del cliente, en la región de Snowflake que exige la política del cliente: Viewnear despliega en la región de Snowflake que se requiera en toda América, y nada en el modelo de entrega obliga a copiar los datos fuera de ella. Los ingenieros con base en Monterrey, Nuevo León, y en Austin, Texas, acceden a esa cuenta como identidades nombradas con acceso de privilegios mínimos, bajo los controles de acceso y el proceso de cambios del cliente. El linaje y el historial de acceso de Horizon Catalog registran cada acceso, y los datos sensibles se clasifican y enmascaran con etiquetado y políticas de fila y columna desde la primera tabla." },
  { category: "Contratación y revisión de proveedores", q: "¿Qué pasa al final de un proyecto de Viewnear?", a: "Un proyecto de Viewnear termina con un traspaso documentado: los runbooks, la documentación y las sesiones de habilitación se entregan junto con el desarrollo, además de un plan de transición que define quién opera qué cuando Viewnear se retira. El trabajo ya vive en la cuenta de Snowflake, los repositorios y el CI del cliente, así que el equipo interno lo opera y lo amplía desde ahí. La optimización continua, el ajuste de costos y el soporte quedan disponibles para los equipos que los quieren." },
  { category: "Nearshore y el equipo de entrega", q: "¿Cuánto se traslapa el equipo de Monterrey con la jornada laboral de Estados Unidos?", a: "El equipo en Monterrey trabaja en la jornada laboral del cliente y no en la propia, así que un proyecto en horario del centro, del este o de la montaña obtiene una jornada que coincide con la suya. Los standups, los sprint reviews y las juntas de seguimiento ocurren dentro de la jornada del cliente, así que un bloqueo planteado en la mañana se responde ese mismo día y no al día siguiente. Monterrey mantiene el horario estándar del centro (CST) todo el año, una hora menos que el centro de Estados Unidos de marzo a noviembre, y el horario de trabajo absorbe la diferencia." },
  { category: "Nearshore y el equipo de entrega", q: "¿Cómo se atienden los riesgos que se asocian al modelo offshore en un proyecto nearshore?", a: "Viewnear responde al riesgo del modelo offshore con tres mecanismos, no con promesas. Continuidad: un mismo equipo comprometido lleva el trabajo del scope a la operación, sin cambios de personal a mitad del proyecto y sin una pirámide de entrega facturada por hora, y los ingenieros con certificación SnowPro que dimensionan el trabajo son quienes lo construyen. Visibilidad: sesiones de trabajo periódicas, un backlog compartido y puntos de decisión claros mantienen el scope, el presupuesto y las prioridades en manos de los sponsors del cliente. Control: el build corre en la cuenta de Snowflake, los repositorios y el CI del propio cliente, con accesos que el cliente otorga y puede revocar, y el linaje de Horizon Catalog mantiene una traza auditable de lo que cambió." },
  { category: "Contratación y revisión de proveedores", q: "¿Quién es dueño del código y de los modelos de datos que produce un proyecto?", a: "El cliente es dueño de todo lo que produce un proyecto: el código, los modelos de datos, las transformaciones y la documentación, y Viewnear no retiene derechos sobre ese trabajo. El desarrollo ocurre dentro de la cuenta de Snowflake, los repositorios y el CI del cliente desde el primer commit, así que la propiedad queda asentada desde el inicio y no depende de una entrega final. Las herramientas de migración de Snowflake y cualquier software de terceros conservan sus propias licencias." },
];
