/**
 * Regenerate config/reviewed.ts: the date each static page's content last
 * actually changed, taken from git history.
 *
 *   npx tsx scripts/update-reviewed-dates.ts
 *
 * Why a generated committed file rather than a runtime lookup or a build-time
 * `new Date()`:
 *
 * - The 24 static marketing pages had no freshness signal in any channel. Only
 *   the 38 database-driven URLs carried `lastmod`, so 48 of the 124 sitemap
 *   entries (24 pages x 2 locales) told a crawler nothing about recency, and a
 *   commercial page with no date is harder for an answer engine to cite with
 *   confidence.
 * - Stamping the build time instead would be a lie, and a `lastmod` that moves
 *   on every deploy is exactly the signal crawlers learn to discount. This
 *   repository already fixed that failure once for the dynamic URLs.
 * - Git knows the truth: the last commit that touched a page's component or its
 *   message catalogs is the last time its content changed.
 *
 * Run it after a content change and commit the result. If it is stale, the dates
 * are merely older than reality, which is the safe direction to be wrong in.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { STATIC_ROUTES } from "../config/routes";

const ROOT = process.cwd();

/** The page component for a static route ("" is the home page). */
function pageFile(route: string): string {
  const seg = route === "" ? "" : route;
  return path.join("app", "[locale]", "(marketing)", seg, "page.tsx");
}

/**
 * Namespaces shared across many pages: site chrome and common microcopy. Editing
 * one of these must not re-date every page that happens to read it, or the whole
 * file degrades into a build-time stamp with extra steps.
 */
const SHARED_NAMESPACES = new Set([
  "common", "nav", "footer", "sharedUi", "strips", "contentData", "misc",
  "forms", "heroUi", "methodology", "consent", "errorPage", "notFound",
  "articleUi", "homeServer", "partnershipUi", "dataAiUi", "platformUi",
  "approachUi", "migrationsUi",
]);

/**
 * Message namespaces a page reads, scraped from its own source, so the mapping
 * survives the cases where the namespace does not match the path
 * (/nearshore/monterrey -> monterrey.json, /life-at-viewnear -> lifeAtViewnear.json).
 * Shared namespaces are excluded: see SHARED_NAMESPACES.
 */
function namespacesFor(file: string): string[] {
  if (!existsSync(file)) return [];
  const src = readFileSync(file, "utf8");
  const found = new Set<string>();
  for (const m of src.matchAll(/getTranslations\(\s*(?:\{[^}]*namespace:\s*)?"([A-Za-z0-9_.]+)"/g)) {
    const ns = m[1].split(".")[0];
    if (!SHARED_NAMESPACES.has(ns)) found.add(ns);
  }
  return [...found];
}

/** Most recent commit date (YYYY-MM-DD) across a set of paths. */
function lastCommitDate(paths: string[]): string | null {
  const existing = paths.filter((p) => existsSync(path.join(ROOT, p)));
  if (existing.length === 0) return null;
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%cs", "--", ...existing], {
      cwd: ROOT,
      encoding: "utf8",
    }).trim();
    return out || null;
  } catch {
    return null;
  }
}

const rows: { path: string; date: string; from: string }[] = [];
for (const route of STATIC_ROUTES) {
  const page = pageFile(route.path);
  const ns = namespacesFor(path.join(ROOT, page));
  const catalogs = ns.flatMap((n) => [`messages/en/${n}.json`, `messages/es/${n}.json`]);
  const tracked = [page, ...catalogs];
  const date = lastCommitDate(tracked);
  if (!date) {
    console.warn(`  no git date for ${route.path || "/"} (looked at ${tracked.length} paths)`);
    continue;
  }
  rows.push({ path: route.path, date, from: `${page}${ns.length ? ` + ${ns.join(", ")}` : ""}` });
}

rows.sort((a, b) => (a.path < b.path ? -1 : 1));

const body = `// GENERATED by scripts/update-reviewed-dates.ts. Do not edit by hand.
//
// The date each static page's content last changed, from git history. Feeds
// \`lastmod\` for the static half of the sitemap. Regenerate after a content
// change:  npx tsx scripts/update-reviewed-dates.ts
//
// Being stale only makes a date older than reality, which is the safe direction:
// a \`lastmod\` that moves on every deploy is the signal crawlers discount.

/** Static route path (as in config/routes.ts) to ISO date of its last content change. */
export const PAGE_UPDATED: Record<string, string> = {
${rows.map((r) => `  ${JSON.stringify(r.path)}: "${r.date}",`).join("\n")}
};
`;

writeFileSync(path.join(ROOT, "config/reviewed.ts"), body);
console.log(`Wrote config/reviewed.ts with ${rows.length} dates`);
for (const r of rows) console.log(`  ${r.date}  ${r.path || "/"}`);
